DROP TABLE IF EXISTS users;
CREATE TABLE users (
  
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  
  email TEXT NOT NULL,
  password TEXT NOT NULL,

  name TEXT NOT NULL,
  
  solved_challenges TEXT NOT NULL,

  last_submission integer not null,
  score integer not null

);

DROP TABLE IF EXISTS training;
CREATE TABLE training (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  
  name TEXT NOT NULL,
  author TEXT NOT NULL,
    
  category TEXT NOT NULL,  
  description TEXT NOT NULL,
  image TEXT NOT NULL
);

DROP TABLE IF EXISTS challenges;
CREATE TABLE challenges (
  
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  
  name TEXT NOT NULL,
  author TEXT NOT NULL,
  
  prompt TEXT NOT NULL,
  possible_answers TEXT NOT NULL, 
  points INTEGER NOT NULL,
  downloadable_files TEXT NOT NULL, 
  hint TEXT NOT NULL,
  
  association TEXT NOT NULL

);

DROP TABLE IF EXISTS writeups;
CREATE TABLE writeups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  
  name TEXT NOT NULL,
  author TEXT NOT NULL,
  association TEXT NOT NULL,

  body TEXT NOT NULL
);

INSERT INTO training (name, author, category, description,  image ) VALUES ( 'PicoCTF 2014', 'John Hammond', 'wargame', '<p>PicoCTF is a computer security game targeted at middle and high school students. The game consists of a series of challenges centered around a unique storyline where participants must reverse engineer, break, hack, decrypt, or do whatever it takes to solve the challenge. The challenges are all set up with the intent of being hacked, making it an excellent, legal way to get hands-on experience. </p><p>', '/static/training_pictures/picoctf_2014.png' );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Tyrannosaurus Hex', 'John Hammond', '    The contents of the flash drive appear to be password protected. On the back of the flash drive, you see the hexadecimal number 0x4355a5e6 scribbled in ink. The password prompt, however, only accepts decimal numbers. What number should you enter? ', '1129686502', 10, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'No Comment', 'John Hammond', "The CD you find has a copy of your father's website: homepage.html. Maybe something is hidden in the site...<br><span style='color:red'> NOTE: This is automatically generated challenge, so the flag will be different from user to user. Since this challenge only requires you to view the source, just submit this flag: <code>flag_f43cece2fb3bafc134c8056464abd793b9c3b8ce</code></span>", 'flag_f43cece2fb3bafc134c8056464abd793b9c3b8ce', 20, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Common Vulnerability Exercise', 'John Hammond', "This disc is encrypted. The surprisingly elaborate password hint refers to 'the CVE Identifier for a 2014 vulnerability that allowed arbitrary code execution in Firefox via a buffer overflow in a speech codec'. If you found this 'CVE-ID' thingy, it'd probably be the password. ", 'CVE-2014-1542', 20, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Caesar', 'John Hammond', "    You find an encrypted message written on the documents. Can you decrypt it? <br><span style='color:red'> NOTE: This is automatically generated challenge, so the flag will be different from user to user. Use this ciphertext: <code>qebpbzobqmxppmeoxpbfpmnezwrsraakxlqbguvdcgvkavseawh</code></span>    ", 'PQHCZUVUDDNAOTEJXYGFJYNDYVHDZK', 20, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'The Valley of Fear', 'John Hammond', 'The hard drive may be corrupted, but you were able to recover a small chunk of text. Scribbled on the back of the hard drive is a set of mysterious numbers. Can you discover the meaning behind these numbers? (1, 9, 4) (4, 2, 8) (4, 8, 3) (7, 1, 5) (8, 10, 1) ', 'Ceremonial plates', 20, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Internet Inspection', 'John Hammond', "On his computer, your father left open a browser with the Thyrin Lab Website. Can you find the hidden access code?<br><span style='color:red'> NOTE: This is automatically generated challenge, so the flag will be different from user to user. Since this challenge asks you to just view the page with developer tools, use this flag: <code>flag_e8f910e5f83893d2f7bc1229ca444cdc03be56d2</code></span>", 'flag_e8f910e5f83893d2f7bc1229ca444cdc03be56d2', 30, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Pickle Jar', 'John Hammond', 'The police station offers free pickles to police officers. However, someone stole the pickles from the pickle jar! You find a clue on a USB drive left at the scene of the crime.', 'YOUSTOLETHEPICKLES', 30, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'RoboPhoto', 'John Hammond', "Your father has been known to use the titles of his favorite books as passwords. While you don't remember any of the names of the books, your father keeps a poster for one of them on his wall. Can you figure out the name of the book and unlock the CD? ", 'The Positronic Man', 30, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'This is the Endian', 'John Hammond', "This is the end! Solving this challenge will help you defeat Daedalus's cyborg. You can find more information about endianness and the problem here. The flag is the smallest possible program input that causes the program to print 'Access Granted'.", 'cveR!edo', 40, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Intercepted Post', 'John Hammond', "We intercepted some of your Dad's web activity. Can you get a password from his traffic?. You can also view the traffic on CloudShark.", 'flag{pl$_$$l_y0ur_l0g1n_form$}', 40, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Supercow', 'John Hammond', 'Daedalus Corp. has a special utility for printing .cow files at /home/daedalus/supercow. Can you figure out how to get it to print out the flag?', 'cows_drive_mooooving_vans', 40, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Grep is Still Your Friend', 'John Hammond', "On his computer, your father left open a browser with the Thyrin Lab Website. Can you find the hidden access code?<br><span style='color:red'> NOTE: This is automatically generated challenge, so the flag will be different from user to user. Since this challenge asks you to just use grep, use this flag: <code>b2bee8664b754d0c85c4c0303134bca6</code></span>", 'b2bee8664b754d0c85c4c0303134bca6', 40, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Javascrypt', 'John Hammond', "Tyrin Robotics Lab uses a special web site to encode their secret messages. Can you determine the value of the secret key? <br><span style='color:red'> NOTE: This is automatically generated challenge, so the flag will be different from user to user. Use these values for the variable: <code>var i = 1; var x = 172; var n = 5493;</code></span>", 'flag_3855', 40, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Easy Overflow', 'John Hammond', "Is the sum of two positive integers always positive? <code>nc vuln2014.picoctf.com 50000</code> 'nc' is the Linux netcat command. Try running it in the shell.", 'That_was_easssy!', 40, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Write Right', 'John Hammond', 'Can you change the secret? The binary can be found at /home/write_right/ on the shell server.', 'arbitrary_write_is_always_right', 50, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Overflow 1', 'John Hammond', 'This problem has a buffer overflow vulnerability! Can you get a shell, then use that shell to read flag.txt? You can solve this problem interactively here, and the source can be found here. ', 'ooh_so_critical', 50, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Redacted', 'John Hammond', " You found <a href='https://2014.picoctf.com/problem-static/forensics/redacted/Redacted.pdf'>a letter</a> that may shed light on recent events. ", 'one_two_three_four', 50, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Toaster Control', 'John Hammond', "  Daedalus Corp. uses a <a href='http://web2014.picoctf.com/toaster-control-1040194/'>web interface</a> to control some of their toaster bots. It looks like they removed the command 'Shutdown & Turn Off' from the control panel. Maybe the functionality is still there... ", 'flag_c49bdkeekr5zqgvc20vc', 50, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'ZOR', 'John Hammond', "  Daedalus has encrypted their blueprints! Can you get us the password?  <br><span style='color:red'> NOTE: This is automatically generated challenge, so the flag will be different from user to user. To submit the flag for this challenge, enter the MD5SUM of the decrypted message <i> up until the actual flag </i> (space included). </span>", '77b21e4a3d02a71f818991ccf392f3e5', 50, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Substitution', 'John Hammond', "  There's an authorization code for some Thyrin Labs information here, along with someone's favorite song. But it's been encrypted! Find the authorization code.  <br><span style='color:red'> NOTE: This is automatically generated challenge, so the flag will be different from user to user. Use the file downloaded here. </span>", 'awholenewworld', 50, 'picoctf_2014/substitution.txt', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Function Address', 'John Hammond', "  We found this program file on some systems. But we need the address of the 'find_string' function to do anything useful! Can you find it for us? ", '08048444', 60, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Basic ASM', 'John Hammond', "  We found this program, but we're having some trouble figuring it out. What's the value of %eax when the last instruction (the NOP) runs?   <br><span style='color:red'> NOTE: This is automatically generated challenge, so the flag will be different from user to user. Use the file downloaded here. </span>", '177651584', 60, 'picoctf_2014/basic_asm.txt', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Spoof Proof', 'John Hammond', "  The police have retrieved a network trace of some suspicious activity. Most of the traffic is users viewing their own profiles on a social networking website, but one of the users on the network downloaded a file from the Thyrin Labs VPN and spoofed their IP address in order to hide their identity. Can you figure out the last name of person that accessed the Thyrin files, and the two source IP addresses they used?[Example valid flag format: 'davis,192.168.50.6,192.168.50.7']", 'johnson,192.168.50.4,192.168.50.3', 60, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Delicious!', 'John Hammond', '  You have found the administrative control panel for the Daedalus Coperation Website: https://web2014.picoctf.com/delicious-5850932/login.php. Unfortunately, it requires that you be logged in. Can you find a way to convince the web site that you are, in fact, logged in?', 'session_cookies_are_the_most_delicious', 60, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Format', 'John Hammond', '  This program is vulnerable to a format string attack! See if you can modify a variable by supplying a format string! The binary can be found at /home/format/ on the shell server. The source can be found here. ', 'who_thought_%n_was_a_good_idea?', 70, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Repeated XOR', 'John Hammond', "  There's a secret passcode hidden in the robot's 'history of cryptography' module. But it's encrypted! Here it is, hex-encoded: encrypted.txt. Can you find the hidden passcode? <br><span style='color:red'> NOTE: This is automatically generated challenge, so the flag will be different from user to user. Use the file downloaded here. </span>", '1dd2a52a367b19748bba4ab6a53b03f1226da5bd', 70, 'picoctf_2014/repeated_xor.txt', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Overflow 2', 'John Hammond', '  This problem has a buffer overflow vulnerability! Can you get a shell? ', 'controlling_%eip_feels_great', 70, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Guess', 'John Hammond', '  This program requires you to guess a random 32-bit number! Sounds difficult, right? There is a server running at vuln2014.picoctf.com:4546, and the source can be found here. ', 'leak_the_seakret', 75, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Cyborg Secrets', 'John Hammond', '  You found a password protected binary on the cyborg relating to its defensive security systems. Find the password and get the shutdown code! You can find it on the shell server at /home/cyborgsecrets/cyborg-defense or you can download it here.', '403-shutdown-for-what', 80, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Droid App', 'John Hammond', "  An Android application was released for the toaster bots, but it seems like this one is some sort of debug version. Can you discover the presence of any debug information being stored, so we can plug this?You can download the apk <a href='https://2014.picoctf.com/problem-static/forensics/DroidApp/ToasterBot.apk'>here</a>. ", 'what_does_the_logcat_say', 80, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Snapcat', 'John Hammond', "  It was found that a Daedalus employee was storing his personal files on a work computer. Unfortunately, he corrupted the filesystem before we could prove it. Can you take a look? Download <a href='https://2014.picoctf.com/problem-static/forensics/snapcat/disk.img'>here</a>. ", 'i_can_has_cheezburger', 80, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'RSA', 'John Hammond', "  A Daedalus Corp spy sent an RSA-encrypted message. We got their key data, but we're not very good at math. Can you decrypt it? Here's the data. Note that the flag is not a number but a number decoded as ASCII text.", 'modular_arithmetics_not_so_bad_after_all!', 80, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'ExecuteMe', 'John Hammond', '  This program will run whatever you send to it! Try to get the flag! The binary can be found at /home/execute/ on the shell server. The source can be found here.', 'shellcode_is_kinda_cool', 80, '', '', (SELECT id FROM training WHERE name = 'PicoCTF 2014') );

INSERT INTO training (name, author, category, description, image ) VALUES ( 'OverTheWire - Bandit', 'John Hammond', 'wargame', '<p>The Bandit wargame is aimed at absolute beginners. It will teach the basics needed to be able to play other wargames.</p><p>This game, like most other games, is organised in levels. You start at Level 0 and try to "beat" or "finish" it. Finishing a level results in information on how to start the next level. The pages on this website for "Level <X>" contain information on how to start level X from the previous level. E.g. The page for Level 1 has information on how to gain access from Level 0 to Level 1.</p><p>You will encounter many situations in which you have no idea what you are supposed to do. <b>Dont panic! Dont give up!</b> The purpose of this game is for you to learn the basics. Part of learning the basics, is reading a lot of new information.</p>', '/static/training_pictures/overthewire.png' );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 0', 'John Hammond', 'The goal of this level is for you to log into the game using SSH. The host to which you need to connect is <b>bandit.labs.overthewire.org</b>, on port <code>2220</code>. The username is <code>bandit0</code> and the password is <code>bandit0</code>. <br><br>The password for the next level is stored in a file called readme located in the home directory. Use this password to log into bandit1 using SSH. Whenever you find a password for a level, use SSH (on port 2220) to log into that level and continue the game.', 'gtVrDuiDfck831PqWsLEZy5gyDz1clto', 5, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 1', 'John Hammond', 'The password for the next level is stored in a file called - located in the home directory', 'ZluruAthQk7Q2MqmDeTiUij2ZvWy2mBi', 5, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 2', 'John Hammond', 'The password for the next level is stored in a file called spaces in this filename located in the home directory', 'sJIJNW6ucpu6HPZ1ZAchaDtwd7oGrD14', 5, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 3', 'John Hammond', '    The password for the next level is stored in a hidden file in the inhere directory.', 'Z9tkRkWmpt9Qr7XrR5jWRkgOU901swEZ', 5, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 4', 'John Hammond', 'The password for the next level is stored in the only human-readable file in the inhere directory. Tip: if your terminal is messed up, try the "reset" command.', 'iX6IOfmpN7AYOQGPwtn3fXpbaJVJcHfq', 10, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 5', 'John Hammond', 'The password for the next level is stored in a file somewhere under the inhere directory and has all of the following properties: - human-readable - 1033 bytes in size - not executable', 'aGoY4q2Dc6MgDq4oL4YtoKtyAg9PeHa1', 10, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 6', 'John Hammond', 'The password for the next level is stored somewhere on the server and has all of the following properties: - owned by user bandit7 - owned by group bandit6 - 33 bytes in size', '7z3hEENjQtflzgnT29q7wAvMNfZdh0i9', 10, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 7', 'John Hammond', 'The password for the next level is stored in the file data.txt next to the word millionth', 'DBfUBfqQG69KvJvJ1iAbMoIpwSNQ9bWe', 10, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 8', 'John Hammond', 'The password for the next level is stored in the file data.txt and is the only line of text that occurs only once', 'UsvVyFSfZZWbi6wgC7dAFyFuR6jQQUhR', 10, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 9', 'John Hammond', "The password for the next level is stored in the file data.txt in one of the few human-readable strings, beginning with several '=' characters.", 'truKLdjsbJ5g7yyJ2X2R0o3a5HQJFuLk', 15, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 10', 'John Hammond', 'The password for the next level is stored in the file data.txt, which contains base64 encoded data', 'IFukwKGsFW8MOq3IRFqrxE1hxTNEbUPR', 15, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 11', 'John Hammond', 'The password for the next level is stored in the file data.txt, where all lowercase (a-z) and uppercase (A-Z) letters have been rotated by 13 positions', '5Te8Y4drgCRfCx8ugdwuEX8KFC6k2EUu', 15, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 12', 'John Hammond', 'The password for the next level is stored in the file data.txt, which is a hexdump of a file that has been repeatedly compressed. For this level it may be useful to create a directory under /tmp in which you can work using mkdir. For example: mkdir /tmp/myname123. Then copy the datafile using cp, and rename it using mv (read the manpages!)', '8ZjyCRiBWFYkneahHwxCv3wb2a1ORpYL', 15, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 13', 'John Hammond', "The password for the next level is stored in /etc/bandit_pass/bandit14 and can only be read by user bandit14. For this level, you don't get the next password, but you get a private SSH key that can be used to log into the next level. Note: localhost is a hostname that refers to the machine you are working on", '4wcYUJFw0k0XLShlDzztnTBHiqxU3b3e', 15, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 14', 'John Hammond', 'The password for the next level can be retrieved by submitting the password of the current level to port 30000 on localhost.', 'BfMYroe26WYalil77FoDi9qh59eK5xNr', 20, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 15', 'John Hammond', '    The password for the next level can be retrieved by submitting the password of the current level to port 30001 on localhost using SSL encryption. <br>    Helpful note: Getting "HEARTBEATING" and "Read R BLOCK"? Use -ign_eof and read the "CONNECTED COMMANDS" section in the manpage. Next to R and Q, the B command also works in this version of that command...', 'cluFn7wTiGryunymYOu4RcffSxQluehd', 20, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 16', 'John Hammond', "The credentials for the next level can be retrieved by submitting the password of the current level to a port on localhost in the range 31000 to 32000. First find out which of these ports have a server listening on them. Then find out which of those speak SSL and which don't. There is only 1 server that will give the next credentials, the others will simply send back to you whatever you send to it. <br><span style='color:red'>To submit this flag for the USCGA Cyber Team, submit the <code>md5sum</code> of the obtained private key file. </span>", '571163e61081adffbc20b27d17647cf0', 20, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 17', 'John Hammond', "    There are 2 files in the homedirectory: passwords.old and passwords.new. The password for the next level is in passwords.new and is the only line that has been changed between passwords.old and passwords.new <br>    NOTE: if you have solved this level and see 'Byebye!' when trying to log into bandit18, this is related to the next level, bandit19 ", 'kfBf3eYk5BPBRzwjqutbbfE887SVc5Yd', 20, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 18', 'John Hammond', 'The password for the next level is stored in a file readme in the homedirectory. Unfortunately, someone has modified .bashrc to log you out when you log in with SSH.', 'IueksS7Ubh8G3DCwVzrTd8rAVOwq3M5x', 20, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 19', 'John Hammond', 'To gain access to the next level, you should use the setuid binary in the homedirectory. Execute it without arguments to find out how to use it. The password for this level can be found in the usual place (/etc/bandit_pass), after you have used the setuid binary.', 'GbKksEFF4yrVs6il55v6gwY5aVje5f0j', 25, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 20', 'John Hammond', '    There is a setuid binary in the homedirectory that does the following: it makes a connection to localhost on the port you specify as a commandline argument. It then reads a line of text from the connection and compares it to the password in the previous level (bandit20). If the password is correct, it will transmit the password for the next level (bandit21).   <br>    NOTE: To beat this level, you need to login twice: once to run the setuid command, and once to start a network daemon to which the setuid will connect.<br>    NOTE 2: Try connecting to your own network daemon to see if it works as you think', 'gE269g2h3mw3pwgrj0Ha9Uoqen1c9DGr', 25, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 21', 'John Hammond', 'A program is running automatically at regular intervals from cron, the time-based job scheduler. Look in /etc/cron.d/ for the configuration and see what command is being executed.', 'Yk7owGAcWjwMVRwrTesJEwB7WVOiILLI', 25, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 22', 'John Hammond', '    A program is running automatically at regular intervals from cron, the time-based job scheduler. Look in /etc/cron.d/ for the configuration and see what command is being executed.    <br>    NOTE: Looking at shell scripts written by other people is a very useful skill. The script for this level is intentionally made easy to read. If you are having problems understanding what it does, try executing it to see the debug information it prints.', 'jc1udXuA1tiHqjIsL8yaapX5XIAI6i0n', 25, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 23', 'John Hammond', '    A program is running automatically at regular intervals from cron, the time-based job scheduler. Look in /etc/cron.d/ for the configuration and see what command is being executed.    <br>    NOTE: This level requires you to create your own first shell-script. This is a very big step and you should be proud of yourself when you beat this level!    <br>    NOTE 2: Keep in mind that your shell script is removed once executed, so you may want to keep a copy around...', 'UoMYTrfrBFHyQXmg6gzctqAwOmw1IohZ', 35, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 24', 'John Hammond', 'A daemon is listening on port 30002 and will give you the password for bandit25 if given the password for bandit24 and a secret numeric 4-digit pincode. There is no way to retrieve the pincode except by going through all of the 10000 combinations, called brute-forcing.', 'uNG9O58gUE7snukf3bvZ0rxhtnjzSGzG', 35, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Bandit - Level 25', 'John Hammond', 'Logging in to bandit26 from bandit25 should be fairly easy... The shell for user bandit26 is not /bin/bash, but something else. Find out what it is, how it works and how to break out of it.', '5czgV9L3Xx8JPOyRbXh6lQbmIOWvPT6Z', 35, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Bandit') );

INSERT INTO training (name, author, category, description,  image ) VALUES ( 'OverTheWire - Natas', 'John Hammond', 'wargame', "<p> Natas teaches the basics of server-side web-security.</p><p>Each level of natas consists of its own website located at http://natasX.natas.labs.overthewire.org, where X is the level number. There is no SSH login. To access a level, enter the username for that level (e.g. natas0 for level 0) and its password.</p><p>Each level has access to the password of the next level. Your job is to somehow obtain that next password and level up. All passwords are also stored in <code>/etc/natas_webpass/</code>. E.g. the password for natas5 is stored in the file <code>/etc/natas_webpass/natas5</code> and only readable by natas4 and natas5.</p><p><b> Start here: </b> Username: <code>natas0</code> Password: <code>natas0</code> URL: <a href='http://natas0.natas.labs.overthewire.org'>http://natas0.natas.labs.overthewire.org</a></p>", '/static/training_pictures/overthewire.png' );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 0', 'John Hammond', 'There is no information for this level, intentionally.', 'gtVrDuiDfck831PqWsLEZy5gyDz1clto', 5, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 1', 'John Hammond', 'There is no information for this level, intentionally.', 'ZluruAthQk7Q2MqmDeTiUij2ZvWy2mBi', 5, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 2', 'John Hammond', 'There is no information for this level, intentionally.', 'sJIJNW6ucpu6HPZ1ZAchaDtwd7oGrD14', 5, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 3', 'John Hammond', '    There is no information for this level, intentionally.', 'Z9tkRkWmpt9Qr7XrR5jWRkgOU901swEZ', 5, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 4', 'John Hammond', 'There is no information for this level, intentionally.', 'iX6IOfmpN7AYOQGPwtn3fXpbaJVJcHfq', 10, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 5', 'John Hammond', 'There is no information for this level, intentionally.', 'aGoY4q2Dc6MgDq4oL4YtoKtyAg9PeHa1', 10, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 6', 'John Hammond', 'There is no information for this level, intentionally.', '7z3hEENjQtflzgnT29q7wAvMNfZdh0i9', 10, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 7', 'John Hammond', 'There is no information for this level, intentionally.', 'DBfUBfqQG69KvJvJ1iAbMoIpwSNQ9bWe', 15, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 8', 'John Hammond', 'There is no information for this level, intentionally.', 'W0mMhUcRRnG8dcghE4qvk3JA9lGt8nDl', 15, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 9', 'John Hammond', 'There is no information for this level, intentionally.', 'nOpp1igQAkUzaI1GUUjzn1bFVj7xCNzu', 25, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 10', 'John Hammond', 'There is no information for this level, intentionally.', 'U82q5TCMMQ9xuFoI3dYX61s7OZD9JKoK', 30, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 11', 'John Hammond', 'There is no information for this level, intentionally.', 'EDXp0pS26wLKHZy1rDBPUZk0RKfLGIR3', 35, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 12', 'John Hammond', 'There is no information for this level, intentionally.', 'jmLTY0qiPZBbaKc9341cqPQZBJv7MQbY', 50, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 13', 'John Hammond', 'There is no information for this level, intentionally.', 'Lg96M10TdfaPyVBkJdjymbllQ5L6qdl1', 60, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 14', 'John Hammond', 'There is no information for this level, intentionally.', 'AwWj0w5cvxrZiONgZ9J5stNVkmxdk39J', 80, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 15', 'John Hammond', 'There is no information for this level, intentionally.', 'WaIHEacj63wnNIBROHeqi3p9t0m5nhmh', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 16', 'John Hammond', 'There is no information for this level, intentionally.', '8Ps3H0GWbn5rd9S7GmAdgQNdkhPkq9cw', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 17', 'John Hammond', 'There is no information for this level, intentionally.', 'xvKIqDjy4OPv7wCRgDlmj0pFsCsDjhdP', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 18', 'John Hammond', 'There is no information for this level, intentionally.', '4IwIrekcuZlA9OsjOkoUtwU6lhokCPYs', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 19', 'John Hammond', 'There is no information for this level, intentionally.', 'eofm3Wsshxc5bwtVnEuGIlr7ivb9KABF', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 20', 'John Hammond', 'There is no information for this level, intentionally.', 'IFekPyrQXftziDEsUr3x21sYuahypdgJ', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 21', 'John Hammond', 'There is no information for this level, intentionally.', 'chG9fbe1Tq2eWVMgjYYD1MsfIvN461kJ', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 22', 'John Hammond', 'There is no information for this level, intentionally.', 'D0vlad33nQF0Hz2EP255TP5wSW9ZsRSE', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 23', 'John Hammond', 'There is no information for this level, intentionally.', 'OsRmXFguozKpTZZ5X14zNO43379LZveg', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 24', 'John Hammond', 'There is no information for this level, intentionally.', 'GHF6X7YwACaYYssHVY05cFq83hRktl4c', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 25', 'John Hammond', 'There is no information for this level, intentionally.', 'oGgWAJ7zcGT28vYazGo4rkhOPDhBu34T', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 26', 'John Hammond', 'There is no information for this level, intentionally.', '55TBjpPZUUJgVP5b3BnbG6ON9uDPVzCJ', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 27', 'John Hammond', 'There is no information for this level, intentionally.', 'JWwR438wkgTsNKBbcJoowyysdM82YjeF', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Natas - Level 28', 'John Hammond', 'There is no information for this level, intentionally.', 'airooCaiseiyee8he8xongien9euhe8b', 100, '', '', (SELECT id FROM training WHERE name = 'OverTheWire - Natas') );

INSERT INTO training (name, author, category, description,  image ) VALUES ( "John's 2016 Challenges", 'John Hammond', 'homemade', '<p>These challenges were all made locally by John.</p>', '' );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Warmup <code>(misc)</code>', 'John Hammond', "<p> It's everyone's favorite!</p>", 'USCGA{let_me_show_you_the_ropes}', 25, 'kitty.jpg', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Irregular Expressions <code>(web)</code>', 'John Hammond', '<p> Check out our new regular expressions testbed! Now you can test your regex online at <a href="http://10.6.1.7:5555"><code>http://10.6.1.7:5555</code></a></p>', 'USCGA{php_preg_replace_may_be_dangerous}', 100, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Linux Kiosk <code>(misc)</code>', 'John Hammond', '<p> This public computer kiosk is weird! It just offers the man page for <code>less</code>? </p><p>Connect to it here: <code> ssh user@10.6.1.7 -p 1888 </code></p><p>Username is <code>user</code> and password is <code>userpass</code></p>', 'USCGA{less_is_more!!!}', 80, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( '1-800-RSA-TODAY <code>(crypto)</code>', 'John Hammond', '<p> My phone bill is through the roof! I called Bob, but Eve found my public key!</p>', 'USCGA{simple_rsa?_no_way!}', 100, 'cipher.wav<DELIMETER>pubkey.pem', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Buff the Barque <code>(pwn)</code>', 'John Hammond', '<p> We all hate it, but we all have to do it.</p><p>Board the barque with <code>nc 10.6.1.7 9999</code>.Download the barque here.</p>', 'USCGA{if_only_eagle_would_buffer_overflow}', 150, 'eagle', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'LSB <code>(stego)</code>', 'John Hammond', "<p> Ah, bonjour mon bon ami! Bienvenue a la capture du drapeau! J'ai entendu dire que vous etiez fan de la steganographie! Avez-vous deja entendu parler d'un outil appele zsteg?</p></p>", 'USCGA{lsb_est_mon_bon_ami}', 80, 'pierre.png', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'GLHF <code>(web)</code>', 'John Hammond', '<p> LMFAO! FLAG PLZ, THX! </p><p></p><p><a href="http://10.6.1.7:1337/">http://10.6.1.7:1337/</a></p>', 'USCGA{lmfao_php_filters_ftw!!!}', 120, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Count Dracula <code>(pwn)</code>', 'John Hammond', '<p> I like to count! Count, count, count!  </p><p></p><p>Count with me at <code>nc 10.6.1.7 7777</code></p>', 'USCGA{2147483647_thats_the_number_of_the_day}', 70, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'TackStack <code>(pwn)</code>', 'John Hammond', '<p> Have you ever played Jenga? Tack Stack is like that game, but with tacks! </p><p></p><p><code>nc 10.6.1.7 3456</code></p>', 'USCGA{tack_stack?_more_like_stack_attack}', 175, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Dairy Products <code>(web)</code>', 'John Hammond', '<p> There is a new advertising campaign on the classic dairy company&apos;s website. You need to steal their latest product. </p><p></p><p><a href="http://10.6.1.7:5777/">http://10.6.1.7:5777/</a></p>', "USCGA{you_git'em_got'em_good}", 125, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Recipes&trade; <code>(web)</code>', 'John Hammond', '<p> It&apos;s online social network, but for bakers and hackers alike!Add your recipe online at<a href="http://10.6.1.7/recipes/">http://10.6.1.7/recipes/</a></p>', 'USCGA{admin_cookies_yum!}', 100, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'QUACK <code>(misc)</code>', 'John Hammond', '<p> We found this binary on a USB drive someone left lying around. There was a note attached, that read: "you&apos;re the one."</p>', 'USCGA{ducky_not_just_for_bath_tubs}', 110, 'quack.bin', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'WhitePages <code>(stego)</code>', 'John Hammond', '<p>I stopped using YellowPages and moved onto WhitePages... but the book they gave me is all blank!</p>', 'USCGA{not_all_spaces_are_created_equal}', 90, 'whitepages.txt', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( '2048 <code>(misc)</code>', 'John Hammond', '<p>cGx6aGVscG1l</p>', 'USCGA{i_hope_you_didnt_use_asciitohex.com}', 90, '2048.zip', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Quick Run <code>(misc)</code>', 'John Hammond', '<p>You gotta go fast!</p>', 'USCGA{zbarimg_makes_qrcodes_easy}', 80, 'quick_run.zip', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( "John's Password Pickler <code>(re/pwn)</code>", 'John Hammond', '<p>Check out this new tool I found, it&apos;s called "John&apos;s Password Pickler!"The author thinks he can keep passwords secure. Prove him wrong by tryingto steal his!</p><p>You can download the source here, but you can interact with the program remotely at <br> <code>nc 10.6.1.7 1347</code></p><p><b> Note: the flag format <code>USCGA{the_password}</code></b></p>', 'USCGA{ilovepickles}', 150, 'server.py', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Loopback <code>(network)</code>', 'John Hammond', '<p>Hello? Hello? Oh hello! Oh hello!</p>', 'USCGA{icmp_is_the_protocol_for_me}', 115, 'sniffed.pcap', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Obfuscabyss <code>(misc)</code>', 'John Hammond', "<p>I dropped my flag... and now it's locked away in all these strange obfuscations!</p>", 'USCGA{how_did_you_find_me}', 90, 'obfuscabyss', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'seed sPRiNG <code>(pwn/crypto)</code>', 'John Hammond', '<p>The most revolutionary game is finally available: SEED sPRiNG is open <b><i>right now!</i></b></p><p>Connect here: <code>nc 10.6.1.7 1846</code></p>', 'USCGA{pseudo_random_number_generator_not_so_random}', 200, 'seed_spring', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'CALC-UL8R <code>(misc)</code>', 'John Hammond', '<p>Texas Instruments latest new product: <i>you</i>!</p><p>Connect here: <code>nc 10.6.1.7 6995</code></p>', 'USCGA{sympy_to_solve_equations}', 150, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Chasm <code>(misc)</code>', 'John Hammond', "<p>The Internet's new echo server. Break it.</p><p>Connect here: <code>nc 10.6.1.7 7312</code></p>", 'USCGA{dangerous_echoes_in_this_chasm}', 100, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'The Czar <code>(misc/crypto)</code>', 'John Hammond', '<p>A classic... but with some twists!</p><pre>\\xf1\\xf1\\xe9\\xdf\\xed\\xcb\\xe1\\xd2\\xfc\\xf2\\xf5\\x02\\xfd\\xcd\\xd0\\x0f\\x01\\xf1\\xd4\\x06\\xf4\\xf2\\xf1\\x16\\xf4\\xf3\\xe5\\x02\\xfc\\xcd\\xd0\\x08\\x00\\xcc\\xd4\\x05\\xf4\\xf3\\xe9\\x08\\xe9\\x06\\xed\\xd4</pre>', 'USCGA{if_only_caesar_knew_base64}', 100, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Old Monitor <code>(crypto)</code>', 'John Hammond', '<p>I have this old CRT monitor that I use for my desktop computer. It crashed on me and spit out all these weird numbers...</p>', 'USCGA{the_chinese_remainder_theorem_is_so_cool}', 150, 'old_monitor.zip', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Disco Dancer <code>(misc)</code>', 'John Hammond', "<p>I'm feeling so <em>antsy</em>, it's time for Dance Dance Revolution!</p>", 'USCGA{PIL_to_process_images}', 125, 'disco_dancer.png', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Hot Dog <code>(crypto)</code>', 'John Hammond', "<p>This isn't a problem with the grill.</p>", 'USCGA{looks_like_wieners_on_the_barbecue}', 200, 'hotdog.txt', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Magician <code>(web)</code>', 'John Hammond', '<p>Show me a hat trick. <a href="http://10.6.1.7:1338">http://10.6.1.7:1338</a></p>', 'USCGA{magic_hashes_make_for_a_good_show}', 100, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Pyg-Pen <code>(pwn/misc)</code>', 'John Hammond', '<p>Oh no! We are locked in a pyg-pen! Help us break out. <code>nc 10.6.1.7 3987</code></p>', 'USCGA{python_jail_cant_hold_us_back}', 150, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( '2xPAD <code>(crypto)</code>', 'John Hammond', '<p>The latest and greatest encryption scheme, "two-time pad" is twice as secure as one time pads. Check it out:</p>', 'USCGA{dont_reuse_your_keys}', 125, 'encrypted_one.png<DELIMETER>encrypted_two.png', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Sequelitis <code>(web)</code>', 'John Hammond', '<p>Sequelitis has moved to a new database for keeping track of their customers. Break in. <a href="http://10.6.1.7:555">http://10.6.1.7:555</a></p>', 'USCGA{explicit_sqli_is_how_sql_will_die}', 125, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Eyeless <code>(web)</code>', 'John Hammond', '<p>My roommate just made this cool site. I wonder how secure it is...</p><p><a href="http://10.6.1.7:2297/">http://10.6.1.7:2297</a></p>', 'USCGA{BLIND_SQL_INJECTION_CANT_BE_DONE_WITH_BRAILLE}<DELIMETER>USCGA{blind_sql_injection_cant_be_done_with_braille}<DELIMETER>uscga{blind_sql_injection_cant_be_done_with_braille}', 150, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'Meme Factory <code>(web)</code>', 'John Hammond', '<p>I don&apos;t always make CTF challenges... but when I do, they&apos;re full of memes. <a href="http://10.6.1.7:5000/">http://10.6.1.7:5000/</a><br><br><b>Source code is called: <code>memeserver.py</code></b></p>', 'USCGA{i_herd_u_liek_flags}', 250, 'memeserver.py_download', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'pdfmax <code>(misc/pwn)</code>', 'John Hammond', '<p>pdfmax version 1.0! The new online cloud interpreter. All a student could ever need! <code> nc 10.6.1.7 5895</code></p>', 'USCGA{write18_my_flag_down_immediately}', 100, '', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );
INSERT INTO challenges (name, author, prompt, possible_answers, points, downloadable_files, hint, association) VALUES ( 'shattered <code>(misc)</code>', 'John Hammond', '<p>Remember Bsides? If only we knew about <a href="http://www.circlemud.org/jelson/software/tcpflow/"><b><code>tcpflow</code></b></a>...</p><p><b> Wrap the flag in the typical "USCGA{}" format. </b></p>', 'USCGA{unshattered.jpg}', 80, 'shattered.pcapng', '', (SELECT id FROM training WHERE name = "John's Local Challenges") );

INSERT INTO training (name, author, category, description,  image ) VALUES ( "Micro Corruption", 'John Hammond', 'wargame', '', '' );
INSERT INTO training (name, author, category, description,  image ) VALUES ( "Cyberstakes 2015", 'John Hammond', 'wargame', '', '/static/training_pictures/cyberstakes.png' );
INSERT INTO training (name, author, category, description,  image ) VALUES ( "All-Army Cyberstakes 2016", 'John Hammond', 'wargame', '', '' );
INSERT INTO training (name, author, category, description,  image ) VALUES ( "Matasano Cryptopals", 'John Hammond', 'wargame', '', '' );
INSERT INTO training (name, author, category, description,  image ) VALUES ( "Smash The Stack - IO", 'John Hammond', 'wargame', '', '/static/training_pictures/smash_the_stack.png' );
INSERT INTO training (name, author, category, description,  image ) VALUES ( "Under The Wire", 'John Hammond', 'wargame', '', '' );
INSERT INTO training (name, author, category, description,  image ) VALUES ( "pwnable.kr", 'John Hammond', 'wargame', '', '' );