# -*- mode: ruby -*-
# vi: set ft=ruby :

$provision = <<SCRIPT
hostname portal
echo portal > /etc/hostname
SCRIPT

Vagrant.configure("2") do |config|
	config.vm.provision "shell", inline: $provision
	config.vm.define "user_vm" do |user_vm| 
	user_vm.vm.box = "hashicorp/precise64" ; end
;; end
